# ['chess', 'heads', 'fire', 'office', 'pumpkin', 'redkitchen', 'stairs']

data:
    dataset: 'NeRFMatchPair'
    data_dir: 'data/7scenes'
    scenes: ['chess']
    scene_anno_path: 'data/annotations/7scenes_jsons/sfm/transforms_#scene_#split.json'    
    scene_dir: 'outputs/scene_dirs/7scenes/sfm/inter_layer3/#scene/mip/last_15ep/ds8lin'
    train_pair_txt: 'data/pairs/7scenes/#scene/pairs-db-covis30.txt'
    test_pair_txt: 'data/pairs/7scenes/#scene/pairs-query-densevlad10.txt'
    pair_topk: 30
    img_wh: [480, 480]
    img_dim: 3
    use_msk: False
    model_ds: 8
    balanced_pair: True
    imagenet_norm: True
    epoch_sample_num: 10000
    aug_self_pairs: 10

optim:
    optimizer: 'adam'
    adapt_lr: True
    clr: 0.0004
    cbs: 16
    weight_decay: 0.0
    lr_scheduler: 'cosine'

model:
    backbone: 'convformer384'
    pretrained: True
    im_pe: True
    im_sa_type: 'share'
    im_sa: 3
    temp_type: 'mul'

    # pt enc
    pt_sa: 3
    pt_dim: 256
    pt_sa_type: 'full'
    pt_pe: True
    pt_pe_type: 'fourier'
    post_pt_pe: True

    # Matching
    cfeat_dim: 256
    ffeat_dim: 128
    cformer_type: 'crs'
    coarse_layers: 1
    pt_ftype: 'nerf'
    fine_sa: 1
    fsa_type: 'full'
    win_sz: 5
    cat_c_feat: True

    # Training
    fine_loss: 'match'
    coarse_percent: 0.3
    coarse_dthres: 10

exp:
    seed: 12343
    odir: 'outputs/nerfmatch/c2f/7scenes/sfm'
    prefix: 'eccv/perscene'
    resume_version: 'mip_inter3'
    num_workers: 4
    max_epochs: 50
    check_epochs: 1
    batch_size: 2 # for 40GB
    debug: False
